/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowToGetHereRouteImport } from './routes/how-to-get-here'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesIndexRouteImport } from './routes/classes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements/index'
import { Route as AlaCarteIndexRouteImport } from './routes/ala-carte/index'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ClassesSlugRouteImport } from './routes/classes/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiSiteInfoRouteImport } from './routes/api/site-info'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAlaCarteOrdersRouteImport } from './routes/api/ala-carte-orders'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements/$slug'
import { Route as AlaCarteCategoryIdRouteImport } from './routes/ala-carte/$categoryId'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const HowToGetHereRoute = HowToGetHereRouteImport.update({
  id: '/how-to-get-here',
  path: '/how-to-get-here',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlaCarteIndexRoute = AlaCarteIndexRouteImport.update({
  id: '/ala-carte/',
  path: '/ala-carte/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSlugRoute = ClassesSlugRouteImport.update({
  id: '/classes/$slug',
  path: '/classes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteInfoRoute = ApiSiteInfoRouteImport.update({
  id: '/api/site-info',
  path: '/api/site-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlaCarteOrdersRoute = ApiAlaCarteOrdersRouteImport.update({
  id: '/api/ala-carte-orders',
  path: '/api/ala-carte-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlaCarteCategoryIdRoute = AlaCarteCategoryIdRouteImport.update({
  id: '/ala-carte/$categoryId',
  path: '/ala-carte/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/how-to-get-here': typeof HowToGetHereRoute
  '/ala-carte/$categoryId': typeof AlaCarteCategoryIdRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/api/ala-carte-orders': typeof ApiAlaCarteOrdersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/site-info': typeof ApiSiteInfoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/docs/api': typeof DocsApiRoute
  '/ala-carte/': typeof AlaCarteIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/how-to-get-here': typeof HowToGetHereRoute
  '/ala-carte/$categoryId': typeof AlaCarteCategoryIdRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/api/ala-carte-orders': typeof ApiAlaCarteOrdersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/site-info': typeof ApiSiteInfoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/docs/api': typeof DocsApiRoute
  '/ala-carte': typeof AlaCarteIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/classes': typeof ClassesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/how-to-get-here': typeof HowToGetHereRoute
  '/ala-carte/$categoryId': typeof AlaCarteCategoryIdRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/api/ala-carte-orders': typeof ApiAlaCarteOrdersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/api/site-info': typeof ApiSiteInfoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/classes/$slug': typeof ClassesSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/docs/api': typeof DocsApiRoute
  '/ala-carte/': typeof AlaCarteIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/classes/': typeof ClassesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/how-to-get-here'
    | '/ala-carte/$categoryId'
    | '/announcements/$slug'
    | '/api/ala-carte-orders'
    | '/api/health'
    | '/api/openapi'
    | '/api/site-info'
    | '/blog/$slug'
    | '/classes/$slug'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/docs/api'
    | '/ala-carte/'
    | '/announcements/'
    | '/blog/'
    | '/classes/'
    | '/api/auth/$'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/how-to-get-here'
    | '/ala-carte/$categoryId'
    | '/announcements/$slug'
    | '/api/ala-carte-orders'
    | '/api/health'
    | '/api/openapi'
    | '/api/site-info'
    | '/blog/$slug'
    | '/classes/$slug'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/docs/api'
    | '/ala-carte'
    | '/announcements'
    | '/blog'
    | '/classes'
    | '/api/auth/$'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connect'
    | '/contact'
    | '/how-to-get-here'
    | '/ala-carte/$categoryId'
    | '/announcements/$slug'
    | '/api/ala-carte-orders'
    | '/api/health'
    | '/api/openapi'
    | '/api/site-info'
    | '/blog/$slug'
    | '/classes/$slug'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/neon'
    | '/demo/tanstack-query'
    | '/docs/api'
    | '/ala-carte/'
    | '/announcements/'
    | '/blog/'
    | '/classes/'
    | '/api/auth/$'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  HowToGetHereRoute: typeof HowToGetHereRoute
  AlaCarteCategoryIdRoute: typeof AlaCarteCategoryIdRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  ApiAlaCarteOrdersRoute: typeof ApiAlaCarteOrdersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  ApiSiteInfoRoute: typeof ApiSiteInfoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClassesSlugRoute: typeof ClassesSlugRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DocsApiRoute: typeof DocsApiRoute
  AlaCarteIndexRoute: typeof AlaCarteIndexRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-to-get-here': {
      id: '/how-to-get-here'
      path: '/how-to-get-here'
      fullPath: '/how-to-get-here'
      preLoaderRoute: typeof HowToGetHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ala-carte/': {
      id: '/ala-carte/'
      path: '/ala-carte'
      fullPath: '/ala-carte/'
      preLoaderRoute: typeof AlaCarteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$slug': {
      id: '/classes/$slug'
      path: '/classes/$slug'
      fullPath: '/classes/$slug'
      preLoaderRoute: typeof ClassesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-info': {
      id: '/api/site-info'
      path: '/api/site-info'
      fullPath: '/api/site-info'
      preLoaderRoute: typeof ApiSiteInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ala-carte-orders': {
      id: '/api/ala-carte-orders'
      path: '/api/ala-carte-orders'
      fullPath: '/api/ala-carte-orders'
      preLoaderRoute: typeof ApiAlaCarteOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ala-carte/$categoryId': {
      id: '/ala-carte/$categoryId'
      path: '/ala-carte/$categoryId'
      fullPath: '/ala-carte/$categoryId'
      preLoaderRoute: typeof AlaCarteCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  HowToGetHereRoute: HowToGetHereRoute,
  AlaCarteCategoryIdRoute: AlaCarteCategoryIdRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  ApiAlaCarteOrdersRoute: ApiAlaCarteOrdersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  ApiSiteInfoRoute: ApiSiteInfoRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClassesSlugRoute: ClassesSlugRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DocsApiRoute: DocsApiRoute,
  AlaCarteIndexRoute: AlaCarteIndexRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
